### PR TITLE
Strong name signing

### PR DESCRIPTION
**Pull request by deyrajiv**
Signed with strong name to be used in other signed assemblies.

### CODE REVIEW

**Comment by richorama** [comment]
Thanks for this @deyrajiv!

I see the CI is failing becuase the SNK file is missing:

```
msbuild "C:\projects\ironblock\IronBlock.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
CSC : error CS7027: Error signing output with public key from file 'keyPair.snk' -- File not found. [C:\projects\ironblock\IronBlock\IronBlock.csproj]
```

**Comment by deyrajiv** [comment]
Hey!! @richorama Looking into it. Understood the problem will fix it. And do a commit and fresh Pull request

**Comment by richorama** [comment]
cool, thanks! You should be able to push another commit to this one if easier...

**Comment by deyrajiv** [comment]
Well @richorama you may guide how do I do that I have never commited to a open pull request. Will simple commit work

**Comment by richorama** [comment]
no probs! Just commit to you local branch and push to your fork. The PR will automatically update.

**Comment by deyrajiv** [comment]
@richorama Committed the new change  CI is working now. Apologies for the miss.

**Comment by richorama** [comment]
thank you!

**Comment by deyrajiv** [comment]
@richorama Request you to publish the signed Assembly of IronBlock through nuget if that's possible and you are you are willing to.

**Comment by richorama** [comment]
Yup, published as 1.0.6

**Pull request merged**
