### PR TITLE
Add a Blazor sample

### PR DESCRIPTION
**Pull request by ADefWebserver**
image
image
image

### CODE REVIEW

**Comment by richorama** [comment]
This is awesome work - thank you!

I actually played around a little more and got the program to run.

Screenshot from 2020-08-01 21-34-13

Can we host the blazor page from gh-pages, it makes a great example.

**Comment by ADefWebserver** [comment]
My sample is using Server Side Blazor so I don't think you can host it in Github pages :( You would have to re-write it as Blazor WebAssembly.

The [configuration required](https://www.davideguida.com/how-to-deploy-blazor-webassembly-on-github-pages-using-github-actions/) seem like a nightmare (to me at least)...

Are you going to post the code to show how you got the program to run?

**Comment by richorama** [comment]
Sure, the code to run the blockly program is here: https://github.com/richorama/IronBlock/blob/master/BlazorSample/Pages/Index.razor#L239-L254

I might have a go at converting it to web assembly :¬)

**Comment by ADefWebserver** [comment]
> I might have a go at converting it to web assembly :¬)

@richorama - The reason I didn't initially was that I knew it would be a *lot* of code to *securely* transfer the code to the server side parser. Also, unless the parser can also run in WebAssembly, you still can't run the project in GitHub pages, right?

**Comment by richorama** [comment]
I hope that the blockly program will run in web assembly. I guess I'll find out :-)

**Pull request merged**
